server:
 port: 9000
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
    gateway:
      routes:
        - id: test_route
          uri: lb://service-provider/hello/
          predicates:
            - Path=/service-provider/hello/**
  application:
    name: PC-ApiGateWay
